version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - backend/video_storage_server/.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
    - mtstth
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: backend/video_storage_server/.env
    depends_on:
      - database
    ports:
    - "8080:8080"
    networks:
    - mtstth

volumes:
  data:

networks:
  mtstth:
    driver: bridge