basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: rodionyudenko@gmail.com
    name: API Support
  description: This is a service for storing and receiving video.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Video Storage Server API
  version: "1.0"
paths: {}
swagger: "2.0"
